// =============================================================================
// data.js — AUTO-GENERATED by update.py. Do not hand-edit this file.
// Run: python update.py
// Last updated: never (run update.py first)
// =============================================================================

const API_DATA = {
  lastUpdated: null,
  competition: null,
  matches: [],
  standings: [],
  scorers: [],
  drawResults: null,
};
